#! /usr/bin/python -tt
#
# File: fedora-qareviewer
# Author: Toshio Kuratomi <toshio@tiki-lounge.com>
# Date: 29 Feb, 2004
# Copyright: Toshio Kuratomi
# License: GPL
# Description: Graphical program to help write and submit a QA review for a
# Fedora package.
# Id: $Id$
"""Generates a Fedora Style QA Review.
Usage: fedora-qareviewer [OPTIONS] <SRC.RPM>
    -h
    --help              This usage message
    --version           Outputs version and exits

Helps a QA person review an SRPM.  The program contains a simple checklist
and editor to allow the reviewer to fill out boilerplate for what might
be wrong with a package while allowing the user to also add entries for things
the editor does not know about.
"""

__programName__ = "fedora-qareviewer"
__version__ = "0.1"
__revision__ = "$Rev$"

# 8K block size for now.
BLOCKSIZE=8192

import sys

from qareviewer import QAReviewer

if __name__ == "__main__":
    # Setup gnome environment
    # Parse commandline
    # Open the qachecklist
    application = QAReviewer(sys.argv);
    application.mainloop()
    sys.exit(0)
    # class Editor
    # class ChecklistWindow
    # class SaveFile
    # class ChecklistRulesFile
    # Initialize the sourceview
    # If a savefile is given, open that
    # If new then make sure we have both a bugzilla # and an SRPM
    # Pregenerate MD5Sums/Sha1Sums
    # Check package signature
    # unrpm sources to buildroot
